### ISSUE TITLE
Salesforce OAuth not supported

### ISSUE THREAD

**Issue by andrewalbrecht** [Crim/pardot-java-client#58]
"The Pardot API currently requires a Pardot user to access, but starting with the Summer ’20 release the Pardot API will be available to Salesforce users as well. Once available, all Pardot API integrations will need to be updated to authenticate with a Salesforce user before the Spring ’21 release." - https://help.salesforce.com/articleView?siteLang=en_us&id=000353746&language=en_us&type=1&mode=1

It looks like the Salesforce OAuth is currently unsupported (not surprised with its recent implementation). I am currently working on integrating with the Pardot API and may get by with the existing Pardot authentication mechanism with this library, but would need to switch before the cutoff date. This may be something I can do with a little overriding of certain methods, but would prefer a first-class solution in the library itself.

Additional documentation on authentication: https://developer.pardot.com/kb/authentication/

**Comment by Crim** [comment]
Yea that's something that's been on my radar.  Unfortunately at the moment I don't have a Pardot account with Salesforce OAuth enabled on it to test against.  Given this library is used internally, it'll undoubtedly get updated at some point prior to the hard cut off date.   

That said, I definitely welcome contributions if you have the time to put together a proper solution.  Otherwise, I'll start digging around and seeing if I can get my test account setup in a way I can develop this against it.  I feel like ideally the library should handle negotiating with the Salesforce endpoints to get (and renew when needed) the SSO token.

Thanks!

**Comment by Crim** [comment]
Pending release of version 3.0.0 to add support.

**Comment by melloware** [comment]
Excellent. Hopefully our team can be a guinea pig and report any bugs we find.

**Comment by Crim** [comment]
Sounds good!  I haven't cut the 3.0.0 release yet.  There's one more set of breaking changes I want to add into this release and package it all up together.  Likely get it published to maven in another day or two.

Thanks!

**Comment by Crim** [comment]
Published 3.0.0 to maven. Let me know if you run into any troubles.  Thanks!
