### ISSUE TITLE
Turn of Response Logging for queryProspects.

### ISSUE THREAD

**Issue by krutishilp** [Crim/pardot-java-client#76]
I am using ProspectQueryRequest to get Prospects records but it is logging a huge xml response on every request. Is there any way to stop this logging mechanism? 
Thanks in advance :) .

**Comment by Crim** [comment]
Hey,

So I believe this project only uses `slf4j-api` as a logging interface, and doesn't use any specific logging framework:

```xml
<!-- Logging Interface -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
```

So that means you need to configure whatever logging framework your project is setup to use in order to reduce the verbosity.  That makes it a bit difficult for me to give you specific instructions w/o knowing what logging framework/library you're using.

Do you know if you're using log4j? log4j2? logback?

Thanks

**Comment by krutishilp** [comment]
I'm using logback for logging.

**Comment by Crim** [comment]
This may help you learn how to configure logback.  [Link](https://www.baeldung.com/logback).  The section labeled `6.5. Modifying Loggers` talks about how to define what level of logging to show based on classpath.   So for example for a given classpath you could configure it to only show you WARN or ERROR level errors, instead of INFO or DEBUG.

You likely want to configure the log level for class path `com.darksci.pardot.api.rest` to something higher, so instead of logging `INFO` level messages, only `WARN` or higher.

**Comment by krutishilp** [comment]
it works.
Thank you
